// declares all needed variables that are not needed to be declarded in
// the fetch method
const api_key = "98c5425390540d0130eea0cf1a8283d4";
const lat = 40.5999;
const lon = -112.4644;
const url = `https://api.openweathermap.org/data/2.5/forecast?lat=${lat}&lon=${lon}&units=imperial&appid=${api_key}`;
const Monday = document.getElementById("Monday_Day1");
const Tuesday = document.getElementById("Tuesday_Day2");
const Wednesday = document.getElementById("Wednesday_Day3");
const Thursday = document.getElementById("Thursday_Day4");
const Friday = document.getElementById("Friday_Day5");
const Saturday = document.getElementById("Saturday_Day6");
const Sunday = document.getElementById("Sunday_Day0");
const c = console.log;
const cw = console.warn;
const ce = console.error;
let Today = new Date();
let currentDay = document.createElement("h2");
let i;
let tipsArr = [
  "All that glitters is not gold",
  "A picture is worth a thousand words",
  "All good things come to an end",
  "Beggars can’t be choosers",
  "A journey of a thousand miles begins with a single step",
  "A bird in the hand is worth two in the bush",
  "Actions speak louder than words",
  " An apple a day keeps the doctor away",
  "An idle brain is the devil’s workshop",
  "Better safe than sorry",
  "Appearances can be deceptive",
  "A stitch in time saves nine",
  "As you sow, so you shall reap",
  "The grass is always greener on the other side",
  "Beauty is in the eye of the beholder",
  "Better late than never",
  "Blood is thicker than water",
  "When in Rome, do as the Romans do",
  "Don’t count your chickens before they hatch",
  "Don’t judge a book by its cover",
  "Don’t put all your eggs in one basket",
  "Early bird catches the worm",
  "Every cloud has a silver lining",
  "Enjoy it while it lasts",
  "Honesty is the best policy",
  "Haste makes waste",
  "It’s no use crying over spilt milk",
  "Strike while the iron is hot",
  "Laughter is the best medicine",
  "Every dog has its day",
  "The apple doesn’t fall far from the tree",
  "Necessity is the mother of invention",
  "Never put off until tomorrow what you can do today",
  "Practice makes perfect",
  "A friend in need is a friend indeed",
  "Mind your own business",
  "Practice what you preach",
  "Rome wasn’t built in a day",
  "Forgive and forget",
  "Two wrongs don’t make a right",
  "Look before you leap",
  "Fortune favours the bold",
  "Out of sight, out of mind",
  "kill two birds with one stone",
  "Good things come to those who wait",
  "Great minds think alike",
  "Once bitten, twice shy",
  "Money doesn’t grow on trees",
  "The pen is mightier than the sword",
  "Birds of a feather flock together",
  "Absence makes the heart grow fonder",
  "A cat has nine lives",
  "A drowning man will clutch at a straw",
  "A leopard doesn’t change its spots",
  "Alls well that ends well",
  "Among the blind the one-eyed man is king",
  "An empty vessel makes much noise ",
  "A rolling stone gathers no moss",
  "Cleanliness is next to Godliness",
  "Curiosity killed the cat",
  "Practice what you preach",
  "Ignorance is bliss",
  "It’s better to be safe than sorry",
  "It’s easy to be wise after the event",
  "It’s never too late to mend",
  "It’s not over till it’s over",
  "It’s no use crying over spilled milk",
  "Necessity is the mother of invention",
  "Never put off until tomorrow what you can do today",
  "Never test the depth of the water with both feet",
  "No gain without pain",
  "No news is good news",
  "Once bitten twice shy",
  "One man’s junk is another man’s treasure",
  "One shouldn’t miss the forest for the trees",
  "The show must go on",
  "The squeaky wheel gets the grease",
  "Time and tide wait for no man",
  "Too many cooks spoil the broth",
  "Two heads are better than one",
  "What goes around comes around",
  "Where there’s a will, there’s a way",
  "Where there’s smoke there’s fire",
  "Where one door shuts, another opens",
  "While the cat’s away, the mice will play",
  "You can lead a horse to water but you can’t make it drink",
  "Better late than never ",
  "If it ain’t broke, don’t fix it",
  "Desperate times call for desperate measures.",
  "The calm comes before the storm.",
  "A candle loses nothing by lighting another candle.",
  "Bitter pills may have blessed effects.",
  "Familiarity breeds contempt.",
  "The road to hell is paved with good intentions.",
  "Too many chiefs, not enough Indians.",
  "A workman always blames his tools.",
  "A chain is only as strong as its weakest link.",
  "Barking dogs, seldom bite.",
  "Beauty is only skin-deep",
  "Out of the frying pan into the fire.",
];
